DROP TABLE IF EXISTS `DDC_DICTIONARY`;
CREATE TABLE `DDC_DICTIONARY` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `FIELD` varchar(64) NOT NULL DEFAULT '',
  `CODE` varchar(64) NOT NULL DEFAULT '',
  `VALUE` varchar(255) NOT NULL DEFAULT '',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATOR_ID` char(36) DEFAULT NULL,
  `UPDATE_ID` char(36) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `DDC_USER`;
CREATE TABLE `DDC_USER` (
  `ID` char(36) NOT NULL DEFAULT '',
  `LOGIN_ID` varchar(255) NOT NULL DEFAULT '' COMMENT '登录ID',
  `LOGIN_PWD` varchar(255) NOT NULL DEFAULT '' COMMENT '登录密码',
  `STATUS` tinyint(1) NOT NULL DEFAULT '0' COMMENT '状态 0:无效,1:有效',
  `DISPLAY_NAME` varchar(255) NOT NULL DEFAULT '',
  `DESCRIPTION` text COMMENT '描述',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATOR_ID` char(36) DEFAULT NULL,
  `UPDATE_ID` char(36) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `LOGIN_ID` (`LOGIN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;